import 'package:riverpod_annotation/riverpod_annotation.dart';
import '../domain/saved_item.dart';
import '../data/saved_item_repository.dart';
import '../../features/itineraries/presentation/active_itinerary_controller.dart';

part 'save_item_service.g.dart';

class SaveItemService {
  final SavedItemRepository _repository;
  final String Function() _getActiveItineraryId;

  SaveItemService(this._repository, this._getActiveItineraryId);

  /// Save an item to the active itinerary
  /// Deduplication is handled at the repository level via unique constraint
  /// Save an item to the active itinerary
  /// Deduplication is handled at the repository level via unique constraint
  Future<SavedItem> saveItem({
    required ItinerarySection section,
    required String dedupeKey,
    required String title,
    required Map<String, dynamic> details,
    SavedItemExternal? externalData,
    SavedItemTime? time,
    SavedItemLocation? location,
    List<Map<String, dynamic>> media = const [],
  }) async {
    final itineraryId = _getActiveItineraryId();

    final savedItem = SavedItem(
      id: '', // Will be generated by repository
      itineraryId: itineraryId,
      section: section,
      dedupeKey: dedupeKey,
      title: title,
      details: details,
      externalData: externalData,
      time: time,
      location: location,
      media: media,
      sync: const SavedItemSync(status: SyncStatus.queued),
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    return await _repository.saveItem(savedItem);
  }

  /// Unsave an item
  Future<void> unsaveItem(String itemId) async {
    await _repository.deleteItem(itemId);
  }

  /// Get all saved items for the active itinerary
  Future<List<SavedItem>> getSavedItems() async {
    final itineraryId = _getActiveItineraryId();
    return await _repository.getSavedItems(itineraryId);
  }

  /// Get saved items by section
  Future<List<SavedItem>> getSavedItemsBySection(
    ItinerarySection section,
  ) async {
    final itineraryId = _getActiveItineraryId();
    return await _repository.getSavedItemsBySection(itineraryId, section);
  }

  /// Watch saved items for the active itinerary
  Stream<List<SavedItem>> watchSavedItems() {
    final itineraryId = _getActiveItineraryId();
    return _repository.watchSavedItems(itineraryId);
  }

  /// Check if an item is saved
  Future<bool> isItemSaved(String dedupeKey) async {
    final items = await getSavedItems();
    return items.any((item) => item.dedupeKey == dedupeKey);
  }
}

@riverpod
SaveItemService saveItemService(Ref ref) {
  final repository = ref.watch(savedItemRepositoryProvider);

  String getActiveItineraryId() {
    final activeItineraryAsync = ref.read(activeItineraryControllerProvider);
    final activeItinerary = activeItineraryAsync.value;

    if (activeItinerary == null) {
      // This service is transiently instantiated. If we are saving, we usually have a check before.
      // However, for safety, we should probably throw or handle this.
      // If no data is active, we cannot save.
      throw Exception('No active itinerary loaded');
    }
    return activeItinerary.id;
  }

  return SaveItemService(repository, getActiveItineraryId);
}

@riverpod
Stream<List<SavedItem>> savedItems(Ref ref) {
  return ref.watch(saveItemServiceProvider).watchSavedItems();
}
