import 'package:uuid/uuid.dart';
import 'package:dastan/src/features/offline/domain/share_models.dart';
import 'package:dastan/src/features/offline/application/offline_utils.dart';

class ShareService {
  final Uuid _uuid = const Uuid();

  /// Creates a shareable link for an itinerary with the given privacy config.
  Future<ShareLink> createShareLink({
    required String itineraryId,
    required int version,
    required ShareConfig config,
  }) async {
    final now = DateTime.now();
    final expiresAt = config.expiryDays != null
        ? now.add(Duration(days: config.expiryDays!))
        : null;

    final revocationToken = _uuid.v4();

    final shareId = OfflineUtils.generateShareId(
      itineraryId: itineraryId,
      version: version,
      privacyHash: _computePrivacyHash(config),
      expiry: expiresAt ?? DateTime(2099), // Far future if no expiry
    );

    // In a real app, this URL would be generated by a backend service
    final url = 'https://dastan.app/share/$shareId';

    return ShareLink(
      id: shareId,
      itineraryId: itineraryId,
      url: url,
      createdAt: now,
      expiresAt: expiresAt,
      revocationToken: revocationToken,
      config: config,
    );
  }

  /// Revokes a share link (in a real app, this would call a backend).
  Future<void> revokeShare(String shareId, String revocationToken) async {
    // Stub: In production, this would invalidate the share on the server
    await Future.delayed(const Duration(milliseconds: 100));
  }

  /// Applies privacy redactions to data based on config.
  Map<String, dynamic> applyPrivacyRedactions(
    Map<String, dynamic> data,
    ShareConfig config,
  ) {
    final result = Map<String, dynamic>.from(data);

    if (config.excludeNotes) {
      result.remove('notes');
      result.remove('privateNotes');
    }

    if (config.excludePricing) {
      result.remove('price');
      result.remove('cost');
      result.remove('budget');
    }

    if (config.reduceLocationPrecision) {
      // Reduce coordinates to ~11km precision (1 decimal place)
      if (result['latitude'] != null) {
        result['latitude'] = (result['latitude'] as double).roundToDouble();
      }
      if (result['longitude'] != null) {
        result['longitude'] = (result['longitude'] as double).roundToDouble();
      }
    }

    return result;
  }

  String _computePrivacyHash(ShareConfig config) {
    return '${config.reduceLocationPrecision}|${config.excludeNotes}|${config.excludePricing}';
  }
}
